requires 'Minion';
requires 'Mojolicious::Plugin::XslateRenderer';
requires 'Mojolicious::Plugin::RenderFile';
requires 'Mojo::Pg';
requires 'DateTime::Format::Pg';
requires 'Ref::Util';
requires 'MeshMage::DB';
requires 'Net::Subnet';
